project:
  type: website

website:
  title: "LLMs for SQL generation"
  navbar:
    left:
      - href: slides.qmd
        text: Home
      # - about.qmd

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
